// <auto-generated />
using System;
using API;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace API.Migrations
{
    [DbContext(typeof(ContextBP))]
    [Migration("20240206042224_MigrationV1")]
    partial class MigrationV1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("API.Models.Cliente", b =>
                {
                    b.Property<long>("Cliente_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellidos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CEDULA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha_Actualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Fecha_Registro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Cliente_ID");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("API.Models.Cuenta", b =>
                {
                    b.Property<long>("Cuenta_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("Cliente_ID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Fecha_Actualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Fecha_Apertura")
                        .HasColumnType("datetime2");

                    b.Property<long>("Interes_ID")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Monto_Apertura")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Numero_Cuenta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TipoCuenta_ID")
                        .HasColumnType("bigint");

                    b.HasKey("Cuenta_ID");

                    b.ToTable("Cuenta");
                });

            modelBuilder.Entity("API.Models.Intere", b =>
                {
                    b.Property<long>("Interes_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Detalle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Porcentaje")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Interes_ID");

                    b.ToTable("Interes");
                });
#pragma warning restore 612, 618
        }
    }
}
